name: docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install numbox
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install doc dependencies
        run: pip install .[docs]

      - name: Build docs
        run: sphinx-build -b html docs/ docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
          force_orphan: true
