name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            BUILD_VERSION="0.1.${{ github.run_number }}"
            echo "VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
          fi
      - name: Write version to __init__.py
        run: echo "__version__ = '${{ env.VERSION }}'" > numbox/__init__.py

      - name: Build release distributions
        run: |
          python -m pip install build==1.2.2.post1 wheel==0.45.0
          git clean -Xfd
          python -m build --wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/numbox/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
