name: Versioning

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine version
        id: set-version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            BUILD_VERSION="0.0.${{ github.run_number }}"
            echo "VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
          fi
          echo "__version__ = '${VERSION}'" > numbox/__init__.py
